plugins { id 'com.android.application' }
android {
    namespace 'app.ataraxia.social'
    compileSdk 35
    defaultConfig {
        applicationId 'app.ataraxia.social'
        minSdk 30
        targetSdk 35
        versionCode 3
        versionName '0.1.2-stability'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    buildTypes { debug { debuggable false }; release { minifyEnabled false } }
}
